@startuml

entity Transaction {
    + trans_code
    + user_id
    + trans_amount
    + trans_time
    + trans_date
    + trans_type
}

entity User {
    + user_id
    + user_name
}

entity Company {
    + user_id
    + company_name
}

Transaction -- User
User -- Company

@enduml